force-app/main/default/objects/Receipt_Item__c/Receipt_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Item</label>
    <nameField>
        <label>Receipt Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Item__c/fields/Sale__c.field-meta.xml
<CustomField>
    <fullName>Sale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sale</label>
    <referenceTo>Sale__c</referenceTo>
    <relationshipLabel>Receipt Items</relationshipLabel>
    <relationshipName>Receipt_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sale__c/Sale__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <label>Sale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shoes__c/Shoes__c.object-meta.xml
<CustomObject>
    <label>Shoe</label>
    <nameField>
        <label>Shoe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shoes__c/fields/img__c.field-meta.xml
<CustomField>
    <fullName>img__c</fullName>
    <description>Where the image is for this shoe.</description>
    <label>img</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shoes__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shoes__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shoes__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemoController.cls
global with sharing class DemoController {  
    @RemoteAction
    global static Shoes__c[] getShoes() {
        return [SELECT Id, Name, price__c, quantity__c, title__c, img__c FROM Shoes__c LIMIT 20];
    }
    
    @RemoteAction
    global static void makeSale(Receipt_item__c[] saleItems) {
        try {
            Sale__c s = new Sale__c(Name='Sale at ' + DateTime.now().format('yyyy-MMM-dd HH:mm:ss'));
            insert s;
            
            for (Receipt_item__c rItem : saleItems) {
                rItem.Sale__c = s.Id;
                insert rItem;
            }
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }
    }
}